### ISSUE TITLE
安装时出错，PVE 7.3

### ISSUE THREAD

**Issue by levie-vans** [fw867/pve-edge-kernel#59]
![image](https://user-images.githubusercontent.com/66657337/216217084-c0bf9340-d393-4844-ad7d-b658597a3e3b.png)

**Comment by Miroxyz** [comment]
一毛一样的问题

**Comment by ktycky** [comment]
一样一样

**Comment by weiyakeji** [comment]
一样的问题，不清楚什么原因，之前6.05好像还正常，但是现在听说内核主线6.0已经eol了，我还是去玩耍官方的6.1内核了

**Comment by HikaruChang** [comment]
在deb包目錄下執行此script
https://github.com/fw867/pve-edge-kernel/blob/master/scripts/ar.sh

**Comment by levie-vans** [comment]
> 在deb包目錄下執行此script https://github.com/fw867/pve-edge-kernel/blob/master/scripts/ar.sh

感谢。

ChatGPT帮我加了一点进度显示，代码如下:

```
#!/bin/sh

for file in *.deb; do
  echo "Processing $file ..."
  ar x $file
  echo "Unpacking control.tar.zst ..."
  unzstd control.tar.zst
  echo "Unpacking data.tar.zst ..."
  unzstd data.tar.zst
  echo "Compressing control.tar ..."
  xz control.tar
  echo "Compressing data.tar ..."
  xz data.tar
  echo "Removing $file ..."
  rm $file
  echo "Creating new $file ..."
  ar cr $file debian-binary control.tar.xz data.tar.xz
  echo "Removing temporary files ..."
  rm control.tar.zst
  rm data.tar.zst
  rm control.tar.xz
  rm data.tar.xz
  rm debian-binary
done

echo "All done."

```

**Comment by weiyakeji** [comment]
多谢楼上的提醒，现在ai这么牛逼了嘛

**Comment by levie-vans** [comment]
> 多谢楼上的提醒，现在ai这么牛逼了嘛
@weiyakeji 

ChatGPT后来还改了一个用pv工具显示进度条的版本：
```
#!/bin/sh

for file in *.deb; do
  echo "Processing $file"
  ar x "$file" | pv -p -t -e -b > /dev/null
  unzstd control.tar.zst | pv -p -t -e -b > /dev/null
  unzstd data.tar.zst | pv -p -t -e -b > /dev/null
  xz control.tar | pv -p -t -e -b > /dev/null
  xz data.tar | pv -p -t -e -b > /dev/null
  rm "$file"
  ar cr "$file" debian-binary control.tar.xz data.tar.xz | pv -p -t -e -b > /dev/null
  rm control.tar.zst data.tar.zst control.tar.xz data.tar.xz debian-binary
done

```
不过使用之前需要安装pv：

`apt install pv -y`

**Comment by levie-vans** [comment]
ChatGPT给出的解决方案：

<img width="531" alt="Snipaste_2023-02-17_11-56-16" src="https://user-images.githubusercontent.com/66657337/219545865-557a0a09-316e-4b55-bd43-d108b9b9a7f9.png">

**Comment by hikaruchang** [comment]
> > 在deb包目錄下執行此script https://github.com/fw867/pve-edge-kernel/blob/master/scripts/ar.sh
> 
> 感谢。
> 
> ChatGPT帮我加了一点进度显示，代码如下:
> 
> ```
> #!/bin/sh
> 
> for file in *.deb; do
>   echo "Processing $file ..."
>   ar x $file
>   echo "Unpacking control.tar.zst ..."
>   unzstd control.tar.zst
>   echo "Unpacking data.tar.zst ..."
>   unzstd data.tar.zst
>   echo "Compressing control.tar ..."
>   xz control.tar
>   echo "Compressing data.tar ..."
>   xz data.tar
>   echo "Removing $file ..."
>   rm $file
>   echo "Creating new $file ..."
>   ar cr $file debian-binary control.tar.xz data.tar.xz
>   echo "Removing temporary files ..."
>   rm control.tar.zst
>   rm data.tar.zst
>   rm control.tar.xz
>   rm data.tar.xz
>   rm debian-binary
> done
> 
> echo "All done."
> ```

可以，但沒必要。我也係AI project developer，GitHub Copilot在coding方向優於ChatGPT，另外，歡迎使用Bing Image Creator並提出意見 XD
